// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHafta15._02CodeFirst.Data;

#nullable disable

namespace WebHafta15._02CodeFirst.Migrations
{
    [DbContext(typeof(SirketDbContext))]
    [Migration("20241224135657_ilkMigration")]
    partial class ilkMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebHafta15._02CodeFirst.Models.Departman", b =>
                {
                    b.Property<int>("DepartmanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmanId"));

                    b.Property<string>("DepartmanAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DepartmanId");

                    b.ToTable("tb_Departman", (string)null);
                });

            modelBuilder.Entity("WebHafta15._02CodeFirst.Models.Kisi", b =>
                {
                    b.Property<int>("KisiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KisiId"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("KisiId");

                    b.HasIndex("DepartmanId");

                    b.ToTable("tb_Kisi", (string)null);
                });

            modelBuilder.Entity("WebHafta15._02CodeFirst.Models.Kisi", b =>
                {
                    b.HasOne("WebHafta15._02CodeFirst.Models.Departman", "KisiDepartmani")
                        .WithMany("DepartmanKisileri")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KisiDepartmani");
                });

            modelBuilder.Entity("WebHafta15._02CodeFirst.Models.Departman", b =>
                {
                    b.Navigation("DepartmanKisileri");
                });
#pragma warning restore 612, 618
        }
    }
}
