// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHafta15._01DbFirst.Data;

#nullable disable

namespace WebHafta15._01DbFirst.Migrations
{
    [DbContext(typeof(EticaretDbContext))]
    [Migration("20241224123726_ustkategoriNullOlabilir2")]
    partial class ustkategoriNullOlabilir2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Adre", b =>
                {
                    b.Property<int>("AdresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AdresSatir1")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdresSatir2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MahId")
                        .HasColumnType("int");

                    b.HasKey("AdresId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("MahId");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Ilce", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IlceId"));

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.HasKey("IlceId");

                    b.HasIndex("SehirId");

                    b.ToTable("Ilce", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UstKategoriId")
                        .HasColumnType("int");

                    b.HasKey("KategoriId");

                    b.HasIndex("UstKategoriId");

                    b.ToTable("Kategori", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.KategoriOzellik", b =>
                {
                    b.Property<int>("KategoriOzellikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriOzellikId"));

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("OzellikId")
                        .HasColumnType("int");

                    b.HasKey("KategoriOzellikId")
                        .HasName("PK_KategoriOZellik");

                    b.HasIndex("KategoriId");

                    b.HasIndex("OzellikId");

                    b.ToTable("KategoriOzellik", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MailKodu")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("MailOnay")
                        .HasColumnType("bit");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Mahalle", b =>
                {
                    b.Property<int>("MahalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MahalleId"));

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<string>("MahalleAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MahallePostaKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MahalleId");

                    b.HasIndex("IlceId");

                    b.ToTable("Mahalle", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Ozellik", b =>
                {
                    b.Property<int>("OzellikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OzellikId"));

                    b.Property<string>("OzellikAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("OzellikId");

                    b.ToTable("Ozellik", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Satici", b =>
                {
                    b.Property<int>("SaticiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaticiId"));

                    b.Property<string>("SaticiAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SaticiAdres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SaticiMahId")
                        .HasColumnType("int")
                        .HasColumnName("SaticiMahID");

                    b.HasKey("SaticiId");

                    b.HasIndex("SaticiMahId");

                    b.ToTable("Satici", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SaticiUrun", b =>
                {
                    b.Property<int>("SaticiUrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaticiUrunId"));

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("money");

                    b.Property<int>("SaticiId")
                        .HasColumnType("int");

                    b.Property<int>("StokAdedi")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("SaticiUrunId");

                    b.HasIndex("SaticiId");

                    b.HasIndex("UrunId");

                    b.ToTable("SaticiUrun", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Sehir", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SehirId"));

                    b.Property<string>("SehirAdi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("SehirId");

                    b.ToTable("Sehir", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SepetUrun", b =>
                {
                    b.Property<int>("SepetUrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SepetUrunId"));

                    b.Property<bool>("HediyeMi")
                        .HasColumnType("bit");

                    b.Property<int>("SaticiUrunId")
                        .HasColumnType("int");

                    b.Property<int>("SepetKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("UrunAdedi")
                        .HasColumnType("int");

                    b.HasKey("SepetUrunId");

                    b.HasIndex("SaticiUrunId");

                    b.HasIndex("SepetKullaniciId");

                    b.ToTable("SepetUrun", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Sipari", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("OdemeOnayi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime");

                    b.HasKey("SiparisId");

                    b.HasIndex("AdresId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Siparis");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SiparisUrun", b =>
                {
                    b.Property<int>("SiparisUrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisUrunId"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<bool>("HediyeMi")
                        .HasColumnType("bit");

                    b.Property<int>("SatUrunId")
                        .HasColumnType("int");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("SiparisUrunId");

                    b.HasIndex("SatUrunId");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisUrun", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<int>("KatId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UrunId");

                    b.HasIndex("KatId");

                    b.ToTable("Urun", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.UrunOzellik", b =>
                {
                    b.Property<int>("UrunOzellikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunOzellikId"));

                    b.Property<string>("OzellikIcerik")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OzellikId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("UrunOzellikId");

                    b.HasIndex("OzellikId");

                    b.HasIndex("UrunId");

                    b.ToTable("UrunOzellik", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Yorum", b =>
                {
                    b.Property<int>("YorumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YorumId"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int")
                        .HasColumnName("KullaniciID");

                    b.Property<byte>("Puan")
                        .HasColumnType("tinyint");

                    b.Property<int>("SaticiUrunId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime");

                    b.Property<string>("YorumMetin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("YorumId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SaticiUrunId");

                    b.ToTable("Yorum", (string)null);
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Adre", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Kullanici", "Kullanici")
                        .WithMany("Adres")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_Adres_Kullanici");

                    b.HasOne("WebHafta15._01DbFirst.Models.Mahalle", "Mah")
                        .WithMany("Adres")
                        .HasForeignKey("MahId")
                        .IsRequired()
                        .HasConstraintName("FK_Adres_Mahalle");

                    b.Navigation("Kullanici");

                    b.Navigation("Mah");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Ilce", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Sehir", "Sehir")
                        .WithMany("Ilces")
                        .HasForeignKey("SehirId")
                        .IsRequired()
                        .HasConstraintName("FK_Ilce_Sehir");

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Kategori", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Kategori", "UstKategori")
                        .WithMany("InverseUstKategori")
                        .HasForeignKey("UstKategoriId")
                        .IsRequired()
                        .HasConstraintName("FK_Kategori_Kategori");

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.KategoriOzellik", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Kategori", "Kategori")
                        .WithMany("KategoriOzelliks")
                        .HasForeignKey("KategoriId")
                        .IsRequired()
                        .HasConstraintName("FK_KategoriOZellik_Kategori");

                    b.HasOne("WebHafta15._01DbFirst.Models.Ozellik", "Ozellik")
                        .WithMany("KategoriOzelliks")
                        .HasForeignKey("OzellikId")
                        .IsRequired()
                        .HasConstraintName("FK_KategoriOZellik_Ozellik");

                    b.Navigation("Kategori");

                    b.Navigation("Ozellik");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Mahalle", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Ilce", "Ilce")
                        .WithMany("Mahalles")
                        .HasForeignKey("IlceId")
                        .IsRequired()
                        .HasConstraintName("FK_Mahalle_Ilce");

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Satici", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Mahalle", "SaticiMah")
                        .WithMany("Saticis")
                        .HasForeignKey("SaticiMahId")
                        .IsRequired()
                        .HasConstraintName("FK_Satici_Mahalle");

                    b.Navigation("SaticiMah");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SaticiUrun", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Satici", "Satici")
                        .WithMany("SaticiUruns")
                        .HasForeignKey("SaticiId")
                        .IsRequired()
                        .HasConstraintName("FK_SaticiUrun_Satici");

                    b.HasOne("WebHafta15._01DbFirst.Models.Urun", "Urun")
                        .WithMany("SaticiUruns")
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK_SaticiUrun_Urun");

                    b.Navigation("Satici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SepetUrun", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.SaticiUrun", "SaticiUrun")
                        .WithMany("SepetUruns")
                        .HasForeignKey("SaticiUrunId")
                        .IsRequired()
                        .HasConstraintName("FK_SepetUrun_SaticiUrun");

                    b.HasOne("WebHafta15._01DbFirst.Models.Kullanici", "SepetKullanici")
                        .WithMany("SepetUruns")
                        .HasForeignKey("SepetKullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_SepetUrun_Kullanici");

                    b.Navigation("SaticiUrun");

                    b.Navigation("SepetKullanici");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Sipari", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Adre", "Adres")
                        .WithMany("Siparis")
                        .HasForeignKey("AdresId")
                        .IsRequired()
                        .HasConstraintName("FK_Siparis_Siparis");

                    b.HasOne("WebHafta15._01DbFirst.Models.Kullanici", "Kullanici")
                        .WithMany("Siparis")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_Siparis_Kullanici");

                    b.Navigation("Adres");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SiparisUrun", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.SaticiUrun", "SatUrun")
                        .WithMany("SiparisUruns")
                        .HasForeignKey("SatUrunId")
                        .IsRequired()
                        .HasConstraintName("FK_SiparisUrun_SaticiUrun");

                    b.HasOne("WebHafta15._01DbFirst.Models.Sipari", "Siparis")
                        .WithMany("SiparisUruns")
                        .HasForeignKey("SiparisId")
                        .IsRequired()
                        .HasConstraintName("FK_SiparisUrun_Siparis");

                    b.Navigation("SatUrun");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Urun", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Kategori", "Kat")
                        .WithMany("Uruns")
                        .HasForeignKey("KatId")
                        .IsRequired()
                        .HasConstraintName("FK_Urun_Kategori");

                    b.Navigation("Kat");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.UrunOzellik", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Ozellik", "Ozellik")
                        .WithMany("UrunOzelliks")
                        .HasForeignKey("OzellikId")
                        .IsRequired()
                        .HasConstraintName("FK_UrunOzellik_Ozellik");

                    b.HasOne("WebHafta15._01DbFirst.Models.Urun", "Urun")
                        .WithMany("UrunOzelliks")
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK_UrunOzellik_Urun");

                    b.Navigation("Ozellik");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Yorum", b =>
                {
                    b.HasOne("WebHafta15._01DbFirst.Models.Kullanici", "Kullanici")
                        .WithMany("Yorums")
                        .HasForeignKey("KullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_Yorum_Kullanici");

                    b.HasOne("WebHafta15._01DbFirst.Models.SaticiUrun", "SaticiUrun")
                        .WithMany("Yorums")
                        .HasForeignKey("SaticiUrunId")
                        .IsRequired()
                        .HasConstraintName("FK_Yorum_Yorum");

                    b.Navigation("Kullanici");

                    b.Navigation("SaticiUrun");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Adre", b =>
                {
                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Ilce", b =>
                {
                    b.Navigation("Mahalles");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Kategori", b =>
                {
                    b.Navigation("InverseUstKategori");

                    b.Navigation("KategoriOzelliks");

                    b.Navigation("Uruns");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Kullanici", b =>
                {
                    b.Navigation("Adres");

                    b.Navigation("SepetUruns");

                    b.Navigation("Siparis");

                    b.Navigation("Yorums");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Mahalle", b =>
                {
                    b.Navigation("Adres");

                    b.Navigation("Saticis");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Ozellik", b =>
                {
                    b.Navigation("KategoriOzelliks");

                    b.Navigation("UrunOzelliks");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Satici", b =>
                {
                    b.Navigation("SaticiUruns");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.SaticiUrun", b =>
                {
                    b.Navigation("SepetUruns");

                    b.Navigation("SiparisUruns");

                    b.Navigation("Yorums");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Sehir", b =>
                {
                    b.Navigation("Ilces");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Sipari", b =>
                {
                    b.Navigation("SiparisUruns");
                });

            modelBuilder.Entity("WebHafta15._01DbFirst.Models.Urun", b =>
                {
                    b.Navigation("SaticiUruns");

                    b.Navigation("UrunOzelliks");
                });
#pragma warning restore 612, 618
        }
    }
}
